#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ARCHVIQ — developmental brain -> RS4/v4 cyber-calibration cascade v0.2
=======================================================================

EXPERIMENTAL RESEARCH CODE. NOT A CLINICAL OR DIAGNOSTIC TOOL.

Purpose
-------
Consume the frozen physical 5/7-day SILSO packet trajectory produced by
`archviq_silso_physical_layer_v0_1.py` and propagate it through an explicit,
auditable hypothesis stack:

    PHYSICAL PACKET
        -> candidate developmental circuit exposure
        -> v4 machine-parameter calibration pressure
        -> recurrent state-dependent cascade
        -> parameter-family hysteresis
        -> H* set-point vector + explanation graph

This version is aligned to the Processing Spiral / RS4-v4 formal specification.
It separates:
  * machine parameters (candidate developmental calibration targets),
  * runtime/content state (sources, memories, active models, current Q_T, etc.), and
  * structural invariants (I1..I6), which are NOT inferred from SSN.

Important scientific boundary
-----------------------------
1. The SILSO packet descriptors and percentiles are outputs of the physical layer.
2. Developmental circuit sensitivity, window->parameter mapping, and directional
   rules are explicit hypotheses. They are NOT fitted biological effect sizes.
3. Natural solar/geomagnetic variability is NOT established as a causal driver of
   fetal neural development by this code.
4. The output is a research calibration vector, not a personality diagnosis,
   disease prediction, or medical conclusion.
5. Runtime RS4-v3.2 numbers are stored as reference baselines only. This code does
   NOT convert developmental calibration states into new literal runtime threshold
   values unless a future validated calibration law is supplied.

Input
-----
Preferred: `packets_all_shifts.csv` from the physical layer.
Required columns include 5/7-day packet identity, W1..F3 window, regime/transition,
and level-conditioned percentiles for the dynamic SSN features.

Developmental windows
---------------------
W1 18..60 dpc
W2 61..100 dpc
W3 101..140 dpc
F1 168..188 dpc
F2 189..202 dpc
F3 203..birth-1

Core outputs
------------
model_config_used.json
formal_spec_manifest.json
invariants_manifest.json
parameter_definitions.csv
developmental_parameter_map.csv
packet_drivers.csv
brain_circuit_trajectory.csv
machine_parameter_trajectory.csv
machine_profile_by_run.csv
machine_profile_ensemble.csv
H_star_vector.json
brain_exposure_ensemble.csv
window_cascade_summary.csv
explanation_graph.json
lesion_manifest.json
(optional) ablation_sensitivity.csv

Example
-------
python3 archviq_brain_cyber_cascade_v0_2_rs4v4.py \
    --packets ARCHVIQ_PHYS_1969_05_19/packets_all_shifts.csv \
    --out ARCHVIQ_RS4V4_1969_05_19 \
    --ablation-suite

Optional engineering ablation (NOT a behavioral lesion validation):
    --ablate NU
    --ablate U
    --ablate GAMMA
    --ablate HYSTERESIS
    --ablate PROVENANCE
    --ablate W_MIN
"""

from __future__ import annotations

import argparse
import json
import math
from copy import deepcopy
from pathlib import Path
from typing import Any, Dict, List, Mapping, MutableMapping, Sequence, Tuple

import numpy as np
import pandas as pd

VERSION = "0.2-rs4v4"
EPS = 1e-12
WINDOW_ORDER = {"W1": 1, "W2": 2, "W3": 3, "F1": 4, "F2": 5, "F3": 6}

# =============================================================================
# FORMAL SPEC MANIFEST
# =============================================================================

RUNTIME_BASELINES = {
    # Frozen RS4 v3.2 reference values from the supplied formal specification.
    # These are NOT rewritten by the developmental layer in v0.2.
    "N_W": 5,
    "THETA_W": 0.50,
    "N_C": 15,
    "M_C": 2,
    "THETA_C": 0.75,
    "THETA_NU": 0.60,
    "D_C": 10,
    "SPAWN_WINDOW": 16,
    "SPAWN_THETA_MISMATCH": 0.30,
    "SPAWN_THETA_R": 0.90,
    "SPAWN_THETA_NU": 0.70,
}

INVARIANTS = {
    "I1": "Reality confirmation must be independent: an item cannot be confirmed by data generated by itself; a memory cannot be confirmed by a derivative of itself.",
    "I2": "Levels cannot be skipped; level 4 (anchor) is reachable only offline through Gamma from level 3.",
    "I3": "Historical source weight cannot override Reality FAIL.",
    "I4": "Compression preserves provenance/source trace.",
    "I5": "Distrust suppresses source influence; it does not invert the source signal.",
    "I6": "w_min > 0: a suppressed source remains recoverable if later reliable.",
}

LESION_EXPECTATIONS = {
    "NU": "Coordinated/correlated false confirmations are no longer discounted; v3.2 toy result cited in spec: 0/40 -> 40/40 fixation when nu is removed.",
    "I1": "Self-confirmation loop: model-generated evidence can consolidate the model that generated it.",
    "GAMMA_ANCHOR_GATE": "Online promotion to anchor becomes possible; belief can become its own Reality reference without offline validation.",
    "W_MIN": "A suppressed source cannot recover after becoming reliable again.",
    "MEMORY_DUAL_TIMESCALE": "One anomalous observation can erase a strong memory trace instead of rapidly lowering use-trust while preserving trace strength.",
    "U": "Error correction is forced onto action/method rather than routing to the appropriate layer/model, producing perseveration when model change is required.",
}

# =============================================================================
# DEFAULT HYPOTHESIS CONFIG
# =============================================================================

CIRCUITS = [
    "BRAINSTEM_HOMEOSTATIC",
    "THALAMUS_TRN",
    "PULVINAR_COHERENCE",
    "SUBPLATE_THALAMOCORTICAL",
    "HIPPOCAMPUS_CONTEXT",
    "AMYGDALA_INSULA",
    "SALIENCE_DACC_INSULA",
    "BASAL_GANGLIA_STN",
    "PFC_REALITY_CONTROL",
    "LONG_RANGE_CORTEX",
    "SLEEP_THALAMOCORTICAL",
]

PARAMETER_DEFINITIONS: Dict[str, Dict[str, Any]] = {
    # Early / base machine calibration
    "GAIN": {
        "label": "general signal gain / excitability calibration",
        "mode": "directional",
        "family": "BASE",
        "positive_meaning": "higher gain / stronger response to perturbation",
        "negative_meaning": "lower gain / weaker response to perturbation",
    },
    "NOISE_SENSITIVITY": {
        "label": "sensitivity to noisy/irregular input",
        "mode": "pressure_only",
        "family": "BASE",
        "positive_meaning": "direction not frozen in v0.2",
        "negative_meaning": "direction not frozen in v0.2",
    },
    "RECOVERY_BASELINE": {
        "label": "baseline return/recovery tendency",
        "mode": "directional",
        "family": "RECOVERY",
        "positive_meaning": "faster return after perturbation",
        "negative_meaning": "slower return / prolonged carry-over",
    },

    # Admission / temporal integration
    "THETA_W": {
        "label": "admission threshold theta_W",
        "mode": "directional",
        "family": "W",
        "runtime_baseline": RUNTIME_BASELINES["THETA_W"],
        "positive_meaning": "higher admission threshold",
        "negative_meaning": "lower admission threshold",
    },
    "THETA_C": {
        "label": "threshold for request of Reality checking theta_C",
        "mode": "directional",
        "family": "W",
        "runtime_baseline": RUNTIME_BASELINES["THETA_C"],
        "positive_meaning": "more evidence/coherence before Reality request",
        "negative_meaning": "earlier Reality request",
    },
    "TAU_INTEGRATION": {
        "label": "temporal integration constant",
        "mode": "directional",
        "family": "W",
        "positive_meaning": "longer temporal integration / longer accumulation",
        "negative_meaning": "shorter temporal integration / faster turnover",
    },

    # nu / cross-channel independence / compression
    "THETA_NU_TIME": {
        "label": "temporal naturalness/regularity threshold component of nu",
        "mode": "pressure_only",
        "family": "NU",
        "runtime_baseline": RUNTIME_BASELINES["THETA_NU"],
        "positive_meaning": "direction not frozen in v0.2",
        "negative_meaning": "direction not frozen in v0.2",
    },
    "THETA_NU_CROSS": {
        "label": "cross-source common-cause/independence threshold component of nu",
        "mode": "pressure_only",
        "family": "NU",
        "runtime_baseline": RUNTIME_BASELINES["THETA_NU"],
        "positive_meaning": "direction not frozen in v0.2",
        "negative_meaning": "direction not frozen in v0.2",
    },
    "THETA_NU_PROVENANCE": {
        "label": "provenance/self-generated evidence threshold component of nu",
        "mode": "pressure_only",
        "family": "NU",
        "runtime_baseline": RUNTIME_BASELINES["THETA_NU"],
        "positive_meaning": "direction not frozen in v0.2",
        "negative_meaning": "direction not frozen in v0.2",
    },
    "M_C": {
        "label": "minimum independent-source requirement M_C",
        "mode": "pressure_only",
        "family": "NU",
        "runtime_baseline": RUNTIME_BASELINES["M_C"],
        "positive_meaning": "direction not frozen in v0.2",
        "negative_meaning": "direction not frozen in v0.2",
    },
    "COMPRESSION_STRENGTH": {
        "label": "degree of recurrent dimensional compression while retaining provenance",
        "mode": "directional",
        "family": "NU",
        "positive_meaning": "stronger compression / higher abstraction tendency",
        "negative_meaning": "weaker compression / more detail retained per level",
    },

    # Consolidation / HOLD
    "D_C": {
        "label": "consecutive-PASS consolidation threshold D_C",
        "mode": "directional",
        "family": "D",
        "runtime_baseline": RUNTIME_BASELINES["D_C"],
        "positive_meaning": "more persistence required before consolidation",
        "negative_meaning": "less persistence required before consolidation",
    },
    "PERSISTENCE": {
        "label": "state persistence / HOLD tendency",
        "mode": "directional",
        "family": "D",
        "positive_meaning": "stronger state persistence",
        "negative_meaning": "greater lability / weaker hold",
    },
    "HOLD_STABILITY": {
        "label": "stability of an already selected processing state",
        "mode": "directional",
        "family": "D",
        "positive_meaning": "more stable HOLD state",
        "negative_meaning": "easier spontaneous state turnover",
    },

    # Decision/action/switch/update
    "THETA_D": {
        "label": "decision threshold",
        "mode": "directional",
        "family": "D",
        "positive_meaning": "more accumulated evidence required to commit decision",
        "negative_meaning": "less evidence required to commit decision",
    },
    "THETA_A": {
        "label": "action threshold",
        "mode": "pressure_only",
        "family": "D",
        "positive_meaning": "direction not frozen in v0.2",
        "negative_meaning": "direction not frozen in v0.2",
    },
    "SWITCH_THRESHOLD": {
        "label": "threshold for switching active state/configuration",
        "mode": "directional",
        "family": "D",
        "positive_meaning": "higher switch threshold",
        "negative_meaning": "lower switch threshold / easier switching",
    },
    "UPDATE_MAGNITUDE": {
        "label": "size of post-threshold update",
        "mode": "directional",
        "family": "U",
        "positive_meaning": "larger update once change occurs",
        "negative_meaning": "smaller incremental update",
    },
    "THETA_U": {
        "label": "model-update threshold",
        "mode": "directional",
        "family": "U",
        "positive_meaning": "more contradiction required before changing model",
        "negative_meaning": "model changes after less contradiction",
    },

    # Explicit hysteresis families
    "HYSTERESIS_W": {
        "label": "history-dependence width for admission/gating",
        "mode": "directional",
        "family": "W",
        "positive_meaning": "wider admission hysteresis band",
        "negative_meaning": "narrower admission hysteresis band",
    },
    "HYSTERESIS_NU": {
        "label": "history-dependence width for nu/common-cause checks",
        "mode": "directional",
        "family": "NU",
        "positive_meaning": "wider nu hysteresis band",
        "negative_meaning": "narrower nu hysteresis band",
    },
    "HYSTERESIS_D": {
        "label": "history-dependence width for HOLD/decision/switch",
        "mode": "directional",
        "family": "D",
        "positive_meaning": "wider HOLD/switch hysteresis band",
        "negative_meaning": "narrower HOLD/switch hysteresis band",
    },
    "HYSTERESIS_U": {
        "label": "history-dependence width for model update",
        "mode": "directional",
        "family": "U",
        "positive_meaning": "wider model-update hysteresis band",
        "negative_meaning": "narrower model-update hysteresis band",
    },

    # Late / meta-control capacities. Several are pressure-only because direction is not frozen.
    "K_ASYMMETRY": {
        "label": "K_down/K_up trust-update asymmetry calibration",
        "mode": "pressure_only",
        "family": "TRUST",
        "positive_meaning": "direction not frozen in v0.2",
        "negative_meaning": "direction not frozen in v0.2",
    },
    "SPAWN_THRESHOLD": {
        "label": "sensitivity/threshold of latent-model spawn",
        "mode": "pressure_only",
        "family": "U",
        "positive_meaning": "direction not frozen in v0.2",
        "negative_meaning": "direction not frozen in v0.2",
    },
    "REALITY_CALIBRATION": {
        "label": "developmental calibration pressure on Reality-monitoring machinery",
        "mode": "pressure_only",
        "family": "REALITY",
        "positive_meaning": "pressure only; no high/low interpretation",
        "negative_meaning": "pressure only; no high/low interpretation",
    },
    "U_ROUTING_CAPACITY": {
        "label": "capacity of error-target routing operator U",
        "mode": "pressure_only",
        "family": "U",
        "positive_meaning": "pressure only; no high/low interpretation",
        "negative_meaning": "pressure only; no high/low interpretation",
    },
    "GAMMA_CAPACITY": {
        "label": "offline sleep recalibration capacity Gamma",
        "mode": "pressure_only",
        "family": "GAMMA",
        "positive_meaning": "pressure only; no high/low interpretation",
        "negative_meaning": "pressure only; no high/low interpretation",
    },
    "ANCHOR_STABILITY": {
        "label": "stability of offline-promoted anchors",
        "mode": "directional",
        "family": "U",
        "positive_meaning": "more stable anchors once established",
        "negative_meaning": "anchors more readily revised",
    },
    "MEMORY_DUAL_TIMESCALE_CAPACITY": {
        "label": "capacity for fast Q_use and slow S_trace memory dynamics",
        "mode": "pressure_only",
        "family": "GAMMA",
        "positive_meaning": "pressure only; no high/low interpretation",
        "negative_meaning": "pressure only; no high/low interpretation",
    },
}

# Relative developmental availability/sensitivity. These are hypothesis coefficients,
# not biological effect sizes. Mostly inherited from v0.1 and explicitly frozen here.
WINDOW_CIRCUIT_SENSITIVITY: Dict[str, Dict[str, float]] = {
    "W1": {
        "BRAINSTEM_HOMEOSTATIC": 0.85, "THALAMUS_TRN": 0.45, "PULVINAR_COHERENCE": 0.10,
        "SUBPLATE_THALAMOCORTICAL": 0.15, "HIPPOCAMPUS_CONTEXT": 0.35, "AMYGDALA_INSULA": 0.55,
        "SALIENCE_DACC_INSULA": 0.15, "BASAL_GANGLIA_STN": 0.30, "PFC_REALITY_CONTROL": 0.05,
        "LONG_RANGE_CORTEX": 0.05, "SLEEP_THALAMOCORTICAL": 0.00,
    },
    "W2": {
        "BRAINSTEM_HOMEOSTATIC": 0.55, "THALAMUS_TRN": 0.70, "PULVINAR_COHERENCE": 0.25,
        "SUBPLATE_THALAMOCORTICAL": 0.85, "HIPPOCAMPUS_CONTEXT": 0.55, "AMYGDALA_INSULA": 0.50,
        "SALIENCE_DACC_INSULA": 0.30, "BASAL_GANGLIA_STN": 0.45, "PFC_REALITY_CONTROL": 0.15,
        "LONG_RANGE_CORTEX": 0.20, "SLEEP_THALAMOCORTICAL": 0.05,
    },
    "W3": {
        "BRAINSTEM_HOMEOSTATIC": 0.40, "THALAMUS_TRN": 0.80, "PULVINAR_COHERENCE": 0.65,
        "SUBPLATE_THALAMOCORTICAL": 0.95, "HIPPOCAMPUS_CONTEXT": 0.65, "AMYGDALA_INSULA": 0.60,
        "SALIENCE_DACC_INSULA": 0.55, "BASAL_GANGLIA_STN": 0.55, "PFC_REALITY_CONTROL": 0.35,
        "LONG_RANGE_CORTEX": 0.60, "SLEEP_THALAMOCORTICAL": 0.15,
    },
    "F1": {
        "BRAINSTEM_HOMEOSTATIC": 0.25, "THALAMUS_TRN": 0.95, "PULVINAR_COHERENCE": 0.80,
        "SUBPLATE_THALAMOCORTICAL": 1.00, "HIPPOCAMPUS_CONTEXT": 0.65, "AMYGDALA_INSULA": 0.65,
        "SALIENCE_DACC_INSULA": 0.70, "BASAL_GANGLIA_STN": 0.80, "PFC_REALITY_CONTROL": 0.65,
        "LONG_RANGE_CORTEX": 0.75, "SLEEP_THALAMOCORTICAL": 0.45,
    },
    "F2": {
        "BRAINSTEM_HOMEOSTATIC": 0.20, "THALAMUS_TRN": 1.00, "PULVINAR_COHERENCE": 0.90,
        "SUBPLATE_THALAMOCORTICAL": 0.85, "HIPPOCAMPUS_CONTEXT": 0.65, "AMYGDALA_INSULA": 0.70,
        "SALIENCE_DACC_INSULA": 0.80, "BASAL_GANGLIA_STN": 1.00, "PFC_REALITY_CONTROL": 0.80,
        "LONG_RANGE_CORTEX": 0.90, "SLEEP_THALAMOCORTICAL": 0.60,
    },
    "F3": {
        "BRAINSTEM_HOMEOSTATIC": 0.15, "THALAMUS_TRN": 0.90, "PULVINAR_COHERENCE": 0.85,
        "SUBPLATE_THALAMOCORTICAL": 0.50, "HIPPOCAMPUS_CONTEXT": 0.85, "AMYGDALA_INSULA": 0.80,
        "SALIENCE_DACC_INSULA": 0.95, "BASAL_GANGLIA_STN": 0.90, "PFC_REALITY_CONTROL": 1.00,
        "LONG_RANGE_CORTEX": 1.00, "SLEEP_THALAMOCORTICAL": 0.90,
    },
}

# Explicit developmental gate: how much each window is allowed to calibrate each
# machine parameter. This is the main v0.2 refactor from the generic v0.1 cyber map.
# Missing entries are zero.
WINDOW_PARAMETER_SENSITIVITY: Dict[str, Dict[str, float]] = {
    "W1": {
        "GAIN": 1.00, "NOISE_SENSITIVITY": 0.85, "RECOVERY_BASELINE": 0.55,
        "THETA_W": 0.30, "THETA_C": 0.15, "TAU_INTEGRATION": 0.25,
        "PERSISTENCE": 0.20, "HOLD_STABILITY": 0.15,
    },
    "W2": {
        "GAIN": 0.35, "NOISE_SENSITIVITY": 0.55, "RECOVERY_BASELINE": 0.35,
        "THETA_W": 1.00, "THETA_C": 1.00, "TAU_INTEGRATION": 0.90,
        "THETA_NU_TIME": 0.25, "THETA_NU_CROSS": 0.20, "THETA_NU_PROVENANCE": 0.20,
        "M_C": 0.35, "COMPRESSION_STRENGTH": 0.25,
        "HYSTERESIS_W": 0.45,
    },
    "W3": {
        "THETA_W": 0.35, "THETA_C": 0.45, "TAU_INTEGRATION": 0.65,
        "THETA_NU_TIME": 1.00, "THETA_NU_CROSS": 1.00, "THETA_NU_PROVENANCE": 0.85,
        "M_C": 0.85, "COMPRESSION_STRENGTH": 1.00,
        "D_C": 0.25, "PERSISTENCE": 0.35, "HOLD_STABILITY": 0.30,
        "HYSTERESIS_W": 0.35, "HYSTERESIS_NU": 0.75,
        "REALITY_CALIBRATION": 0.35,
    },
    "F1": {
        "TAU_INTEGRATION": 0.35, "THETA_NU_CROSS": 0.35, "COMPRESSION_STRENGTH": 0.50,
        "D_C": 1.00, "PERSISTENCE": 1.00, "HOLD_STABILITY": 1.00,
        "THETA_D": 0.35, "SWITCH_THRESHOLD": 0.55,
        "HYSTERESIS_D": 0.80, "HYSTERESIS_NU": 0.30,
        "RECOVERY_BASELINE": 0.35,
    },
    "F2": {
        "D_C": 0.60, "PERSISTENCE": 0.65, "HOLD_STABILITY": 0.65,
        "THETA_D": 1.00, "THETA_A": 0.85, "SWITCH_THRESHOLD": 1.00,
        "UPDATE_MAGNITUDE": 1.00, "THETA_U": 0.45,
        "HYSTERESIS_D": 0.75, "HYSTERESIS_U": 0.45,
        "K_ASYMMETRY": 0.35, "REALITY_CALIBRATION": 0.50,
        "U_ROUTING_CAPACITY": 0.45, "GAMMA_CAPACITY": 0.35,
    },
    "F3": {
        "RECOVERY_BASELINE": 1.00,
        "THETA_D": 0.55, "THETA_A": 0.65, "SWITCH_THRESHOLD": 0.70,
        "UPDATE_MAGNITUDE": 0.80, "THETA_U": 1.00,
        "HYSTERESIS_W": 0.80, "HYSTERESIS_NU": 0.90, "HYSTERESIS_D": 0.80, "HYSTERESIS_U": 1.00,
        "K_ASYMMETRY": 0.80, "SPAWN_THRESHOLD": 0.95,
        "REALITY_CALIBRATION": 1.00, "U_ROUTING_CAPACITY": 1.00,
        "GAMMA_CAPACITY": 1.00, "ANCHOR_STABILITY": 1.00,
        "MEMORY_DUAL_TIMESCALE_CAPACITY": 0.95,
        "COMPRESSION_STRENGTH": 0.70, "THETA_NU_PROVENANCE": 0.55,
    },
}

# Candidate circuit support for each machine parameter. Weights are normalized at runtime.
PARAMETER_CIRCUIT_MAP: Dict[str, Dict[str, float]] = {
    "GAIN": {"BRAINSTEM_HOMEOSTATIC": .30, "THALAMUS_TRN": .25, "AMYGDALA_INSULA": .20, "SALIENCE_DACC_INSULA": .15, "PFC_REALITY_CONTROL": .10},
    "NOISE_SENSITIVITY": {"THALAMUS_TRN": .25, "PULVINAR_COHERENCE": .25, "SUBPLATE_THALAMOCORTICAL": .20, "SALIENCE_DACC_INSULA": .15, "PFC_REALITY_CONTROL": .15},
    "RECOVERY_BASELINE": {"BRAINSTEM_HOMEOSTATIC": .20, "SALIENCE_DACC_INSULA": .25, "PFC_REALITY_CONTROL": .25, "THALAMUS_TRN": .15, "HIPPOCAMPUS_CONTEXT": .15},
    "THETA_W": {"THALAMUS_TRN": .55, "SUBPLATE_THALAMOCORTICAL": .20, "PFC_REALITY_CONTROL": .10, "BASAL_GANGLIA_STN": .10, "SALIENCE_DACC_INSULA": .05},
    "THETA_C": {"THALAMUS_TRN": .35, "PULVINAR_COHERENCE": .20, "SUBPLATE_THALAMOCORTICAL": .20, "PFC_REALITY_CONTROL": .15, "SALIENCE_DACC_INSULA": .10},
    "TAU_INTEGRATION": {"SUBPLATE_THALAMOCORTICAL": .30, "THALAMUS_TRN": .20, "LONG_RANGE_CORTEX": .25, "HIPPOCAMPUS_CONTEXT": .15, "PFC_REALITY_CONTROL": .10},
    "THETA_NU_TIME": {"PULVINAR_COHERENCE": .25, "SUBPLATE_THALAMOCORTICAL": .20, "LONG_RANGE_CORTEX": .20, "HIPPOCAMPUS_CONTEXT": .15, "PFC_REALITY_CONTROL": .10, "THALAMUS_TRN": .10},
    "THETA_NU_CROSS": {"PULVINAR_COHERENCE": .40, "LONG_RANGE_CORTEX": .25, "SUBPLATE_THALAMOCORTICAL": .15, "PFC_REALITY_CONTROL": .10, "HIPPOCAMPUS_CONTEXT": .10},
    "THETA_NU_PROVENANCE": {"HIPPOCAMPUS_CONTEXT": .25, "PFC_REALITY_CONTROL": .25, "LONG_RANGE_CORTEX": .20, "SALIENCE_DACC_INSULA": .15, "THALAMUS_TRN": .15},
    "M_C": {"PULVINAR_COHERENCE": .30, "LONG_RANGE_CORTEX": .25, "PFC_REALITY_CONTROL": .20, "SUBPLATE_THALAMOCORTICAL": .15, "HIPPOCAMPUS_CONTEXT": .10},
    "COMPRESSION_STRENGTH": {"PFC_REALITY_CONTROL": .30, "LONG_RANGE_CORTEX": .30, "HIPPOCAMPUS_CONTEXT": .20, "THALAMUS_TRN": .10, "SALIENCE_DACC_INSULA": .10},
    "D_C": {"PFC_REALITY_CONTROL": .25, "BASAL_GANGLIA_STN": .25, "THALAMUS_TRN": .20, "LONG_RANGE_CORTEX": .15, "SALIENCE_DACC_INSULA": .15},
    "PERSISTENCE": {"BASAL_GANGLIA_STN": .30, "THALAMUS_TRN": .20, "PFC_REALITY_CONTROL": .20, "LONG_RANGE_CORTEX": .15, "SALIENCE_DACC_INSULA": .15},
    "HOLD_STABILITY": {"BASAL_GANGLIA_STN": .35, "THALAMUS_TRN": .20, "PFC_REALITY_CONTROL": .20, "SALIENCE_DACC_INSULA": .15, "LONG_RANGE_CORTEX": .10},
    "THETA_D": {"BASAL_GANGLIA_STN": .40, "PFC_REALITY_CONTROL": .25, "THALAMUS_TRN": .20, "SALIENCE_DACC_INSULA": .15},
    "THETA_A": {"BASAL_GANGLIA_STN": .55, "BRAINSTEM_HOMEOSTATIC": .15, "PFC_REALITY_CONTROL": .15, "SALIENCE_DACC_INSULA": .15},
    "SWITCH_THRESHOLD": {"BASAL_GANGLIA_STN": .35, "THALAMUS_TRN": .30, "PFC_REALITY_CONTROL": .20, "SALIENCE_DACC_INSULA": .15},
    "UPDATE_MAGNITUDE": {"PFC_REALITY_CONTROL": .30, "SALIENCE_DACC_INSULA": .25, "HIPPOCAMPUS_CONTEXT": .20, "BASAL_GANGLIA_STN": .15, "LONG_RANGE_CORTEX": .10},
    "THETA_U": {"PFC_REALITY_CONTROL": .40, "SALIENCE_DACC_INSULA": .25, "HIPPOCAMPUS_CONTEXT": .20, "BASAL_GANGLIA_STN": .15},
    "HYSTERESIS_W": {"THALAMUS_TRN": .35, "PFC_REALITY_CONTROL": .20, "BASAL_GANGLIA_STN": .15, "HIPPOCAMPUS_CONTEXT": .15, "SALIENCE_DACC_INSULA": .15},
    "HYSTERESIS_NU": {"PULVINAR_COHERENCE": .30, "LONG_RANGE_CORTEX": .25, "HIPPOCAMPUS_CONTEXT": .15, "PFC_REALITY_CONTROL": .15, "THALAMUS_TRN": .15},
    "HYSTERESIS_D": {"BASAL_GANGLIA_STN": .30, "PFC_REALITY_CONTROL": .25, "THALAMUS_TRN": .20, "HIPPOCAMPUS_CONTEXT": .15, "SALIENCE_DACC_INSULA": .10},
    "HYSTERESIS_U": {"PFC_REALITY_CONTROL": .30, "HIPPOCAMPUS_CONTEXT": .25, "SALIENCE_DACC_INSULA": .20, "BASAL_GANGLIA_STN": .15, "LONG_RANGE_CORTEX": .10},
    "K_ASYMMETRY": {"SALIENCE_DACC_INSULA": .30, "PFC_REALITY_CONTROL": .25, "HIPPOCAMPUS_CONTEXT": .20, "THALAMUS_TRN": .15, "LONG_RANGE_CORTEX": .10},
    "SPAWN_THRESHOLD": {"PFC_REALITY_CONTROL": .30, "HIPPOCAMPUS_CONTEXT": .25, "SALIENCE_DACC_INSULA": .20, "LONG_RANGE_CORTEX": .15, "BASAL_GANGLIA_STN": .10},
    "REALITY_CALIBRATION": {"PFC_REALITY_CONTROL": .45, "HIPPOCAMPUS_CONTEXT": .20, "LONG_RANGE_CORTEX": .15, "SALIENCE_DACC_INSULA": .10, "THALAMUS_TRN": .10},
    "U_ROUTING_CAPACITY": {"SALIENCE_DACC_INSULA": .40, "PFC_REALITY_CONTROL": .35, "BASAL_GANGLIA_STN": .15, "HIPPOCAMPUS_CONTEXT": .10},
    "GAMMA_CAPACITY": {"SLEEP_THALAMOCORTICAL": .45, "THALAMUS_TRN": .20, "HIPPOCAMPUS_CONTEXT": .20, "PFC_REALITY_CONTROL": .15},
    "ANCHOR_STABILITY": {"HIPPOCAMPUS_CONTEXT": .35, "PFC_REALITY_CONTROL": .30, "LONG_RANGE_CORTEX": .20, "BASAL_GANGLIA_STN": .15},
    "MEMORY_DUAL_TIMESCALE_CAPACITY": {"HIPPOCAMPUS_CONTEXT": .35, "SLEEP_THALAMOCORTICAL": .25, "PFC_REALITY_CONTROL": .20, "THALAMUS_TRN": .10, "LONG_RANGE_CORTEX": .10},
}

# Directional packet-rule weights. Pressure-only parameters deliberately have no
# directional rule in v0.2.
PARAMETER_DRIVER_WEIGHTS: Dict[str, Dict[str, float]] = {
    "GAIN": {"load": .45, "abrupt": .35, "energy": .20},
    "RECOVERY_BASELINE": {"burst_to_quiet": .55, "quiet_after_burst": .25, "repeated_burst": -.35, "load": -.10},
    "THETA_W": {"quiet_to_burst": .35, "persistence": .30, "directionality": .15, "reversal": -.25},
    "THETA_C": {"quiet_to_burst": .25, "persistence": .25, "directionality": .15, "reversal": -.25, "abrupt": .10},
    "TAU_INTEGRATION": {"persistence": .50, "directionality": .20, "reversal": -.35, "quiet": .10},
    "COMPRESSION_STRENGTH": {"persistence": .30, "directionality": .25, "reversal": -.25, "quiet": .10},
    "D_C": {"persistence": .40, "sustained_hold": .25, "quiet_to_burst": .20, "reversal": -.30},
    "PERSISTENCE": {"persistence": .65, "directionality": .20, "reversal": -.40},
    "HOLD_STABILITY": {"persistence": .55, "sustained_hold": .25, "reversal": -.35, "quiet_to_burst": .15},
    "THETA_D": {"quiet_to_burst": .30, "persistence": .25, "directionality": .10, "reversal": -.25, "abrupt": .10},
    "SWITCH_THRESHOLD": {"quiet_to_burst": .45, "persistence": .30, "directionality": .10, "reversal": -.35},
    "UPDATE_MAGNITUDE": {"abrupt": .45, "load": .25, "energy": .20, "quiet_to_burst": .25},
    "THETA_U": {"persistence": .30, "quiet_to_burst": .25, "directionality": .10, "reversal": -.25, "abrupt": .15},
    "HYSTERESIS_W": {"persistence": .30, "quiet_to_burst": .25, "reversal_to_persistent": .20, "persistent_to_reversal": .10, "repeated_reversal": -.20},
    "HYSTERESIS_NU": {"persistence": .20, "directionality": .15, "reversal_to_persistent": .25, "persistent_to_reversal": .15, "repeated_reversal": -.25},
    "HYSTERESIS_D": {"persistence": .30, "quiet_to_burst": .25, "reversal_to_persistent": .25, "persistent_to_reversal": .15, "repeated_reversal": -.20},
    "HYSTERESIS_U": {"persistence": .25, "quiet_to_burst": .25, "abrupt": .20, "reversal_to_persistent": .20, "repeated_reversal": -.15},
    "ANCHOR_STABILITY": {"persistence": .35, "burst_to_quiet": .20, "directionality": .15, "reversal": -.25, "sustained_hold": .20},
}

# Which explicit hysteresis state modulates reversal of each directional parameter.
PARAMETER_HYSTERESIS_LINK: Dict[str, str | None] = {
    "GAIN": None,
    "RECOVERY_BASELINE": None,
    "THETA_W": "HYSTERESIS_W",
    "THETA_C": "HYSTERESIS_W",
    "TAU_INTEGRATION": "HYSTERESIS_W",
    "COMPRESSION_STRENGTH": "HYSTERESIS_NU",
    "D_C": "HYSTERESIS_D",
    "PERSISTENCE": "HYSTERESIS_D",
    "HOLD_STABILITY": "HYSTERESIS_D",
    "THETA_D": "HYSTERESIS_D",
    "SWITCH_THRESHOLD": "HYSTERESIS_D",
    "UPDATE_MAGNITUDE": "HYSTERESIS_U",
    "THETA_U": "HYSTERESIS_U",
    "HYSTERESIS_W": None,
    "HYSTERESIS_NU": None,
    "HYSTERESIS_D": None,
    "HYSTERESIS_U": None,
    "ANCHOR_STABILITY": "HYSTERESIS_U",
}

DEFAULT_CONFIG: Dict[str, Any] = {
    "version": VERSION,
    "status": "experimental_developmental_calibration_model",
    "driver_transform": {"percentile_center": 50.0, "percentile_scale": 50.0, "clip": 1.0},
    "packet_exposure": {"atypicality_weight": 0.70, "abrupt_weight": 0.30},
    "state_update": {
        "activation_threshold": 0.030,
        "reverse_threshold_base": 0.080,
        "reverse_hysteresis_coupling": 0.085,
        "reverse_state_penalty": 0.045,
        "alpha_from_zero": 0.30,
        "alpha_same_sign": 0.34,
        "alpha_reverse": 0.22,
        "retention": 0.994,
        "state_clip": 2.5,
        "same_sign_cascade_gain": 0.12,
        "pressure_retention": 0.94,
        "pressure_alpha": 0.20,
    },
    "circuits": CIRCUITS,
    "window_circuit_sensitivity": WINDOW_CIRCUIT_SENSITIVITY,
    "window_parameter_sensitivity": WINDOW_PARAMETER_SENSITIVITY,
    "parameter_definitions": PARAMETER_DEFINITIONS,
    "parameter_circuit_map": PARAMETER_CIRCUIT_MAP,
    "parameter_driver_weights": PARAMETER_DRIVER_WEIGHTS,
    "parameter_hysteresis_link": PARAMETER_HYSTERESIS_LINK,
    "runtime_baselines": RUNTIME_BASELINES,
    "invariants": INVARIANTS,
}

BURST_REGIMES = {"BURST", "REVERSAL_BURST", "DIRECTED_PERSISTENT_BURST"}
PERSISTENT_REGIMES = {"PERSISTENT", "DIRECTED_PERSISTENT_BURST"}
REVERSAL_REGIMES = {"REVERSAL", "REVERSAL_BURST"}
QUIET_REGIMES = {"QUIET"}

ABLATION_TARGETS = {
    "NU": {"THETA_NU_TIME", "THETA_NU_CROSS", "THETA_NU_PROVENANCE", "M_C", "HYSTERESIS_NU"},
    "U": {"UPDATE_MAGNITUDE", "THETA_U", "HYSTERESIS_U", "SPAWN_THRESHOLD", "U_ROUTING_CAPACITY"},
    "GAMMA": {"GAMMA_CAPACITY", "ANCHOR_STABILITY", "MEMORY_DUAL_TIMESCALE_CAPACITY"},
}

# =============================================================================
# CLI / validation
# =============================================================================

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="ARCHVIQ developmental brain -> RS4/v4 cascade v0.2")
    p.add_argument("--packets", required=True, help="packets_all_shifts.csv from physical layer")
    p.add_argument("--out", required=True, help="output directory")
    p.add_argument("--config", default=None, help="optional JSON config replacing defaults")
    p.add_argument("--top-contributors", type=int, default=15)
    p.add_argument("--ablate", action="append", default=[], choices=["NU", "U", "GAMMA", "HYSTERESIS", "PROVENANCE", "W_MIN"],
                   help="engineering ablation; may be repeated")
    p.add_argument("--ablation-suite", action="store_true", help="run baseline + each supported ablation and write sensitivity table")
    return p.parse_args()


def load_config(path: str | None) -> Dict[str, Any]:
    if path is None:
        return deepcopy(DEFAULT_CONFIG)
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def validate_packets(df: pd.DataFrame) -> None:
    required = {
        "width", "window", "packet_index", "dpc_start", "dpc_end", "regime",
        "dynamic_load_pct", "A_cond_pct", "V_cond_pct", "JUMP_cond_pct",
        "R_cond_pct", "D_cond_pct", "BABS_cond_pct", "ACC_cond_pct",
        "JERK_cond_pct", "E_cond_pct",
    }
    missing = sorted(required - set(df.columns))
    if missing:
        raise ValueError(f"Input packets missing required columns: {missing}")
    if "shift_days" not in df.columns:
        df["shift_days"] = 0
    bad = sorted(set(df["window"].dropna()) - set(WINDOW_ORDER))
    if bad:
        raise ValueError(f"Unexpected developmental windows: {bad}")

# =============================================================================
# Packet drivers
# =============================================================================

def pct_signed(x: float, cfg: Mapping[str, Any]) -> float:
    if not np.isfinite(x):
        return 0.0
    tr = cfg["driver_transform"]
    return float(np.clip((float(x) - float(tr["percentile_center"])) / float(tr["percentile_scale"]),
                         -float(tr["clip"]), float(tr["clip"])))


def regime_flags(prev_regime: str | None, regime: str, prev2_regime: str | None = None) -> Dict[str, float]:
    prev = prev_regime or ""
    prev2 = prev2_regime or ""
    is_burst = regime in BURST_REGIMES
    was_burst = prev in BURST_REGIMES
    is_persistent = regime in PERSISTENT_REGIMES
    was_persistent = prev in PERSISTENT_REGIMES
    is_reversal = regime in REVERSAL_REGIMES
    was_reversal = prev in REVERSAL_REGIMES
    is_quiet = regime in QUIET_REGIMES
    was_quiet = prev in QUIET_REGIMES
    return {
        "quiet_to_burst": float(was_quiet and is_burst),
        "burst_to_quiet": float(was_burst and is_quiet),
        "quiet_after_burst": float(is_quiet and (was_burst or prev2 in BURST_REGIMES)),
        "persistent_to_reversal": float(was_persistent and is_reversal),
        "reversal_to_persistent": float(was_reversal and is_persistent),
        "repeated_burst": float(was_burst and is_burst),
        "repeated_reversal": float(was_reversal and is_reversal),
        "sustained_hold": float(was_persistent and is_persistent),
    }


def packet_drivers(row: Mapping[str, Any], prev_regime: str | None, prev2_regime: str | None,
                   cfg: Mapping[str, Any]) -> Dict[str, float]:
    qA = pct_signed(float(row.get("A_cond_pct", np.nan)), cfg)
    qV = pct_signed(float(row.get("V_cond_pct", np.nan)), cfg)
    qJ = pct_signed(float(row.get("JUMP_cond_pct", np.nan)), cfg)
    qAcc = pct_signed(float(row.get("ACC_cond_pct", np.nan)), cfg)
    qJerk = pct_signed(float(row.get("JERK_cond_pct", np.nan)), cfg)
    qE = pct_signed(float(row.get("E_cond_pct", np.nan)), cfg)
    qR = pct_signed(float(row.get("R_cond_pct", np.nan)), cfg)
    qD = pct_signed(float(row.get("D_cond_pct", np.nan)), cfg)
    qDir = pct_signed(float(row.get("BABS_cond_pct", np.nan)), cfg)
    qLoad = pct_signed(float(row.get("dynamic_load_pct", np.nan)), cfg)

    mag = np.array([qA, qV, qJ, qAcc, qJerk, qE], float)
    abrupt_arr = np.array([qAcc, qJerk, qJ], float)
    d = {
        "load": qLoad,
        "quiet": -qLoad,
        "magnitude": float(np.mean(mag)),
        "atypicality": float(np.mean(np.abs(mag))),
        "abrupt": float(np.mean(abrupt_arr)),
        "energy": qE,
        "persistence": qD,
        "reversal": qR,
        "directionality": qDir,
    }
    d.update(regime_flags(prev_regime, str(row.get("regime", "")), prev2_regime))
    return d

# =============================================================================
# Brain circuit exposure and parameter pressure
# =============================================================================

def normalize_weights(m: Mapping[str, float]) -> Dict[str, float]:
    vals = {k: float(v) for k, v in m.items() if abs(float(v)) > EPS}
    s = sum(abs(v) for v in vals.values())
    return vals if s <= EPS else {k: v / s for k, v in vals.items()}


def circuit_exposure(window: str, drivers: Mapping[str, float], cfg: Mapping[str, Any]) -> Dict[str, float]:
    sens = cfg["window_circuit_sensitivity"][window]
    pe = cfg["packet_exposure"]
    base = float(np.clip(float(pe["atypicality_weight"]) * drivers["atypicality"]
                         + float(pe["abrupt_weight"]) * abs(drivers["abrupt"]), 0.0, 1.0))
    return {c: float(np.clip(float(sens.get(c, 0.0)) * base, 0.0, 1.0)) for c in cfg["circuits"]}


def parameter_circuit_pressure(circuit_pressure: Mapping[str, float], param: str,
                               cfg: Mapping[str, Any]) -> float:
    w = normalize_weights(cfg["parameter_circuit_map"][param])
    return float(np.clip(sum(float(wi) * float(circuit_pressure.get(c, 0.0)) for c, wi in w.items()), 0.0, 1.0))


def developmental_gate(window: str, param: str, cfg: Mapping[str, Any]) -> float:
    return float(cfg["window_parameter_sensitivity"].get(window, {}).get(param, 0.0))


def directional_rule_score(drivers: Mapping[str, float], param: str, cfg: Mapping[str, Any]) -> float:
    mode = str(cfg["parameter_definitions"][param]["mode"])
    if mode != "directional":
        return 0.0
    w = cfg["parameter_driver_weights"].get(param, {})
    if not w:
        return 0.0
    denom = sum(abs(float(x)) for x in w.values())
    if denom <= EPS:
        return 0.0
    score = sum(float(weight) * float(drivers.get(name, 0.0)) for name, weight in w.items()) / denom
    return float(np.clip(score, -1.0, 1.0))

# =============================================================================
# Cascade + explicit parameter-family hysteresis
# =============================================================================

def pressure_update(state: float, pressure: float, cfg: Mapping[str, Any]) -> float:
    su = cfg["state_update"]
    retain = float(su["pressure_retention"])
    alpha = float(su["pressure_alpha"])
    return float(np.clip(retain * state + alpha * pressure * (1.0 - state), 0.0, 1.0))


def hysteretic_update(state: float, drive: float, family_hysteresis_state: float,
                      cfg: Mapping[str, Any], hysteresis_enabled: bool = True) -> Tuple[float, str, float, float]:
    su = cfg["state_update"]
    activation = float(su["activation_threshold"])
    retain = float(su["retention"])
    clip = float(su["state_clip"])

    # Cascade: established same-sign state slightly amplifies repeated same-direction input.
    cascade_gain = 1.0 + float(su["same_sign_cascade_gain"]) * min(abs(state), 1.5) if (state * drive > 0) else 1.0
    drive_eff = float(np.clip(drive * cascade_gain, -1.0, 1.0))

    if abs(drive_eff) < activation:
        return float(np.clip(state * retain, -clip, clip)), "HOLD_NEUTRAL", activation, drive_eff

    same_sign = abs(state) < EPS or np.sign(state) == np.sign(drive_eff)
    if same_sign:
        alpha = float(su["alpha_from_zero"] if abs(state) < EPS else su["alpha_same_sign"])
        new = state + alpha * (drive_eff - state)
        return float(np.clip(new, -clip, clip)), "UPDATE_SAME_SIGN", activation, drive_eff

    if hysteresis_enabled:
        reverse_thr = (
            float(su["reverse_threshold_base"])
            + float(su["reverse_hysteresis_coupling"]) * max(family_hysteresis_state, 0.0)
            + float(su["reverse_state_penalty"]) * min(abs(state), 1.5)
        )
    else:
        reverse_thr = activation

    if abs(drive_eff) < reverse_thr:
        return float(np.clip(state * retain, -clip, clip)), "HOLD_HYSTERESIS", reverse_thr, drive_eff

    alpha = float(su["alpha_reverse"])
    new = state + alpha * (drive_eff - state)
    return float(np.clip(new, -clip, clip)), "UPDATE_REVERSAL", reverse_thr, drive_eff


def ablation_targeted(param: str, ablations: Sequence[str]) -> bool:
    for a in ablations:
        if a in ABLATION_TARGETS and param in ABLATION_TARGETS[a]:
            return True
    return False


def run_one(df_run: pd.DataFrame, cfg: Mapping[str, Any], ablations: Sequence[str] = ()) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, List[Dict[str, Any]], pd.DataFrame]:
    params = list(cfg["parameter_definitions"].keys())
    circuits = list(cfg["circuits"])
    states = {p: 0.0 for p in params}
    pressures = {p: 0.0 for p in params}

    packet_rows: List[Dict[str, Any]] = []
    brain_rows: List[Dict[str, Any]] = []
    traj_rows: List[Dict[str, Any]] = []
    contributors: List[Dict[str, Any]] = []

    g = df_run.copy()
    g["_wo"] = g["window"].map(WINDOW_ORDER)
    g = g.sort_values(["dpc_start", "_wo", "packet_index"]).reset_index(drop=True)

    prev_regime: str | None = None
    prev2_regime: str | None = None
    hyst_enabled = "HYSTERESIS" not in set(ablations)

    for step, (_, row) in enumerate(g.iterrows()):
        drivers = packet_drivers(row, prev_regime, prev2_regime, cfg)
        cexp = circuit_exposure(str(row["window"]), drivers, cfg)
        base_meta = {
            "shift_days": int(row.get("shift_days", 0)),
            "width": int(row["width"]),
            "step": int(step),
            "window": str(row["window"]),
            "packet_index": int(row["packet_index"]),
            "dpc_start": int(row["dpc_start"]),
            "dpc_end": int(row["dpc_end"]),
            "date_start": str(row.get("date_start", "")),
            "date_end": str(row.get("date_end", "")),
            "regime": str(row.get("regime", "")),
            "transition": str(row.get("transition", "")),
        }

        pr = dict(base_meta)
        pr.update(drivers)
        packet_rows.append(pr)
        for c in circuits:
            brain_rows.append({**base_meta, "circuit": c, "exposure_pressure": cexp[c]})

        # Snapshot old state so all parameters update simultaneously and do not depend
        # on arbitrary dictionary order within the same packet.
        old_states = states.copy()
        old_pressures = pressures.copy()
        proposal: Dict[str, Dict[str, Any]] = {}

        for p in params:
            pdef = cfg["parameter_definitions"][p]
            mode = str(pdef["mode"])
            circuit_p = parameter_circuit_pressure(cexp, p, cfg)
            gate = developmental_gate(str(row["window"]), p, cfg)
            packet_pressure = float(np.clip(circuit_p * gate, 0.0, 1.0))

            # Engineering ablation of module families: zero their developmental drive.
            if ablation_targeted(p, ablations):
                packet_pressure = 0.0

            rule = directional_rule_score(drivers, p, cfg)
            signed_drive = float(rule * packet_pressure) if mode == "directional" else 0.0

            hyst_link = cfg["parameter_hysteresis_link"].get(p)
            family_h = float(old_states.get(hyst_link, 0.0)) if hyst_link else 0.0
            new_pressure = pressure_update(old_pressures[p], packet_pressure, cfg)

            if mode == "directional":
                new_state, event, threshold, drive_eff = hysteretic_update(
                    old_states[p], signed_drive, family_h, cfg, hysteresis_enabled=hyst_enabled
                )
            else:
                new_state, event, threshold, drive_eff = old_states[p], "PRESSURE_ONLY", np.nan, 0.0

            proposal[p] = {
                "mode": mode,
                "family": str(pdef.get("family", "")),
                "circuit_pressure": circuit_p,
                "developmental_gate": gate,
                "packet_pressure": packet_pressure,
                "rule_score": rule,
                "signed_drive": signed_drive,
                "drive_effective": drive_eff,
                "family_hysteresis_parameter": hyst_link or "",
                "family_hysteresis_state": family_h,
                "state_before": old_states[p],
                "state_after": new_state,
                "pressure_before": old_pressures[p],
                "pressure_after": new_pressure,
                "delta_state": new_state - old_states[p],
                "hysteresis_event": event,
                "effective_threshold": threshold,
            }

        # Commit simultaneously.
        for p, v in proposal.items():
            states[p] = float(v["state_after"])
            pressures[p] = float(v["pressure_after"])
            traj_rows.append({**base_meta, "parameter": p, **v})
            contributors.append({
                **base_meta,
                "parameter": p,
                "mode": v["mode"],
                "family": v["family"],
                "packet_pressure": v["packet_pressure"],
                "rule_score": v["rule_score"],
                "signed_drive": v["signed_drive"],
                "drive_effective": v["drive_effective"],
                "delta_state": v["delta_state"],
                "hysteresis_event": v["hysteresis_event"],
                "effective_threshold": None if not np.isfinite(v["effective_threshold"]) else float(v["effective_threshold"]),
                "drivers": {k: float(x) for k, x in drivers.items()},
                "top_circuit_pressures": sorted(
                    [{"circuit": c, "pressure": float(cexp[c])} for c in circuits],
                    key=lambda x: x["pressure"], reverse=True
                )[:4],
            })

        prev2_regime = prev_regime
        prev_regime = str(row.get("regime", ""))

    shift = int(g.iloc[0].get("shift_days", 0)) if len(g) else 0
    width = int(g.iloc[0]["width"]) if len(g) else -1
    finals = []
    for p in params:
        pdef = cfg["parameter_definitions"][p]
        finals.append({
            "shift_days": shift,
            "width": width,
            "parameter": p,
            "label": pdef["label"],
            "family": pdef["family"],
            "mode": pdef["mode"],
            "runtime_baseline": pdef.get("runtime_baseline", np.nan),
            "final_calibration_state": states[p],
            "final_calibration_pressure": pressures[p],
            "ablation": "+".join(sorted(set(ablations))) if ablations else "NONE",
        })
    return pd.DataFrame(packet_rows), pd.DataFrame(brain_rows), pd.DataFrame(traj_rows), contributors, pd.DataFrame(finals)

# =============================================================================
# Aggregation / explanation
# =============================================================================

def ensemble_profile(finals: pd.DataFrame) -> pd.DataFrame:
    rows: List[Dict[str, Any]] = []
    for p, g in finals.groupby("parameter", sort=False):
        st = g["final_calibration_state"].to_numpy(float)
        pr = g["final_calibration_pressure"].to_numpy(float)
        pdef = PARAMETER_DEFINITIONS[p]
        rows.append({
            "parameter": p,
            "label": pdef["label"],
            "family": pdef["family"],
            "mode": pdef["mode"],
            "runtime_baseline": pdef.get("runtime_baseline", np.nan),
            "n_runs": int(len(g)),
            "state_median": float(np.median(st)),
            "state_min": float(np.min(st)),
            "state_max": float(np.max(st)),
            "state_iqr": float(np.percentile(st, 75) - np.percentile(st, 25)),
            "pressure_median": float(np.median(pr)),
            "pressure_min": float(np.min(pr)),
            "pressure_max": float(np.max(pr)),
        })
    return pd.DataFrame(rows)


def brain_ensemble(brain: pd.DataFrame) -> pd.DataFrame:
    run = brain.groupby(["shift_days", "width", "circuit"], as_index=False).agg(
        mean_exposure=("exposure_pressure", "mean"), peak_exposure=("exposure_pressure", "max")
    )
    rows = []
    for c, g in run.groupby("circuit", sort=False):
        rows.append({
            "circuit": c,
            "n_runs": int(len(g)),
            "mean_exposure_median": float(g["mean_exposure"].median()),
            "mean_exposure_min": float(g["mean_exposure"].min()),
            "mean_exposure_max": float(g["mean_exposure"].max()),
            "peak_exposure_median": float(g["peak_exposure"].median()),
            "peak_exposure_max": float(g["peak_exposure"].max()),
        })
    return pd.DataFrame(rows)


def window_summary(traj: pd.DataFrame, packet: pd.DataFrame) -> pd.DataFrame:
    pseq = packet.groupby(["shift_days", "width", "window"], as_index=False).agg(
        dpc_start=("dpc_start", "min"), dpc_end=("dpc_end", "max"),
        mean_atypicality=("atypicality", "mean"), mean_abrupt=("abrupt", "mean")
    )
    seq_map: Dict[Tuple[int, int, str], str] = {}
    for key, g in packet.groupby(["shift_days", "width", "window"]):
        seq_map[key] = " | ".join(g.sort_values("dpc_start")["regime"].astype(str))
    pseq["regime_sequence"] = [seq_map[(int(r.shift_days), int(r.width), str(r.window))] for r in pseq.itertuples()]

    mov = traj.groupby(["shift_days", "width", "window", "parameter"], as_index=False)["delta_state"].sum()
    rows = []
    for _, r in pseq.iterrows():
        gg = mov[(mov.shift_days == r.shift_days) & (mov.width == r.width) & (mov.window == r.window)].copy()
        gg["abs_delta"] = gg["delta_state"].abs()
        top = gg.sort_values("abs_delta", ascending=False).head(7)
        rows.append({**r.to_dict(), "top_parameter_changes": " | ".join(f"{x.parameter}:{x.delta_state:+.3f}" for x in top.itertuples())})
    return pd.DataFrame(rows)


def build_explanation_graph(contributors: List[Dict[str, Any]], ensemble: pd.DataFrame, top_n: int,
                            ablations: Sequence[str]) -> Dict[str, Any]:
    out: Dict[str, Any] = {
        "version": VERSION,
        "status": "experimental_hypothesis_graph",
        "warning": "Circuit and developmental mappings are hypotheses; natural EMF causality is not established.",
        "ablation": list(ablations),
        "parameters": {},
    }
    by_param: Dict[str, List[Dict[str, Any]]] = {}
    for x in contributors:
        by_param.setdefault(str(x["parameter"]), []).append(x)
    ens_map = {str(r.parameter): r._asdict() for r in ensemble.itertuples(index=False)}
    for p, arr in by_param.items():
        mode = PARAMETER_DEFINITIONS[p]["mode"]
        if mode == "directional":
            ranked = sorted(arr, key=lambda z: abs(float(z["delta_state"])), reverse=True)
            metric = "abs(delta_state)"
        else:
            ranked = sorted(arr, key=lambda z: float(z["packet_pressure"]), reverse=True)
            metric = "packet_pressure"
        out["parameters"][p] = {
            "definition": PARAMETER_DEFINITIONS[p],
            "ensemble": ens_map.get(p, {}),
            "ranking_metric": metric,
            "top_contributors": ranked[:top_n],
        }
    return out


def h_star_vector(ensemble: pd.DataFrame) -> Dict[str, Any]:
    # H* is represented as the full individual set-point vector, not a scalar.
    vector: Dict[str, Any] = {}
    for r in ensemble.itertuples(index=False):
        vector[str(r.parameter)] = {
            "mode": str(r.mode),
            "family": str(r.family),
            "calibration_state_median": float(r.state_median),
            "calibration_state_range": [float(r.state_min), float(r.state_max)],
            "calibration_pressure_median": float(r.pressure_median),
            "runtime_baseline_reference": None if pd.isna(r.runtime_baseline) else float(r.runtime_baseline),
        }
    return {
        "version": VERSION,
        "definition": "H* is the complete machine-parameter set-point vector. No single H* scalar is inferred.",
        "runtime_projection": "disabled: no validated law maps calibration state to literal RS4 threshold values",
        "vector": vector,
    }


def parameter_definition_table(cfg: Mapping[str, Any]) -> pd.DataFrame:
    rows = []
    for p, d in cfg["parameter_definitions"].items():
        rows.append({"parameter": p, **d})
    return pd.DataFrame(rows)


def developmental_map_table(cfg: Mapping[str, Any]) -> pd.DataFrame:
    rows = []
    for w in WINDOW_ORDER:
        for p in cfg["parameter_definitions"]:
            gate = developmental_gate(w, p, cfg)
            if gate > 0:
                rows.append({"window": w, "parameter": p, "sensitivity": gate, "mode": cfg["parameter_definitions"][p]["mode"], "family": cfg["parameter_definitions"][p]["family"]})
    return pd.DataFrame(rows)

# =============================================================================
# Full run and optional ablation suite
# =============================================================================

def run_model(df: pd.DataFrame, cfg: Mapping[str, Any], ablations: Sequence[str], top_n: int) -> Dict[str, Any]:
    all_packet: List[pd.DataFrame] = []
    all_brain: List[pd.DataFrame] = []
    all_traj: List[pd.DataFrame] = []
    all_contrib: List[Dict[str, Any]] = []
    all_finals: List[pd.DataFrame] = []

    for (_, _), g in df.groupby(["shift_days", "width"], sort=True):
        p, b, t, contrib, f = run_one(g, cfg, ablations=ablations)
        all_packet.append(p); all_brain.append(b); all_traj.append(t); all_contrib.extend(contrib); all_finals.append(f)

    packet_df = pd.concat(all_packet, ignore_index=True)
    brain_df = pd.concat(all_brain, ignore_index=True)
    traj_df = pd.concat(all_traj, ignore_index=True)
    finals_df = pd.concat(all_finals, ignore_index=True)
    ens = ensemble_profile(finals_df)
    bens = brain_ensemble(brain_df)
    wsum = window_summary(traj_df, packet_df)
    graph = build_explanation_graph(all_contrib, ens, max(1, top_n), ablations)
    return {
        "packet": packet_df,
        "brain": brain_df,
        "trajectory": traj_df,
        "finals": finals_df,
        "ensemble": ens,
        "brain_ensemble": bens,
        "window_summary": wsum,
        "graph": graph,
        "hstar": h_star_vector(ens),
    }


def ablation_suite(df: pd.DataFrame, cfg: Mapping[str, Any], baseline_ens: pd.DataFrame, top_n: int) -> pd.DataFrame:
    base = baseline_ens.set_index("parameter")
    suite = ["NU", "U", "GAMMA", "HYSTERESIS", "PROVENANCE", "W_MIN"]
    rows: List[Dict[str, Any]] = []
    for lesion in suite:
        res = run_model(df, cfg, [lesion], top_n=top_n)
        ens = res["ensemble"].set_index("parameter")
        for p in base.index:
            b = base.loc[p]
            a = ens.loc[p]
            rows.append({
                "ablation": lesion,
                "parameter": p,
                "mode": b["mode"],
                "baseline_state_median": float(b["state_median"]),
                "ablated_state_median": float(a["state_median"]),
                "delta_state": float(a["state_median"] - b["state_median"]),
                "baseline_pressure_median": float(b["pressure_median"]),
                "ablated_pressure_median": float(a["pressure_median"]),
                "delta_pressure": float(a["pressure_median"] - b["pressure_median"]),
                "note": (
                    "structural invariant/no numeric developmental lesion in v0.2"
                    if lesion in {"PROVENANCE", "W_MIN"}
                    else "engineering sensitivity only; not behavioral lesion validation"
                ),
            })
    return pd.DataFrame(rows)


def formal_spec_manifest(cfg: Mapping[str, Any]) -> Dict[str, Any]:
    return {
        "version": VERSION,
        "machine_vs_content_separation": {
            "developmentally_calibrated_or_pressured": list(cfg["parameter_definitions"].keys()),
            "runtime_content_not_predicted_from_ssn": [
                "specific source weights w_k", "specific current Q_T", "specific anchors",
                "content of active model M_k", "specific memories", "profession", "beliefs", "subpersonality content"
            ],
            "H_star": "represented by the full final parameter vector, not a scalar",
        },
        "runtime_baselines_reference_only": cfg["runtime_baselines"],
        "nu_decomposition": ["THETA_NU_TIME", "THETA_NU_CROSS", "THETA_NU_PROVENANCE"],
        "hysteresis_decomposition": ["HYSTERESIS_W", "HYSTERESIS_NU", "HYSTERESIS_D", "HYSTERESIS_U"],
        "decision_action_update_separation": ["THETA_D", "THETA_A", "THETA_U"],
        "invariants": cfg["invariants"],
        "scientific_status": {
            "physical_features": "computed from SILSO packet layer",
            "developmental_window_map": "hypothesis",
            "circuit_map": "functional/developmental hypothesis",
            "cyber_mapping": "engineering hypothesis",
            "natural_EMF_causality": "unproven",
            "clinical_use": "not supported",
        },
    }


def main() -> None:
    args = parse_args()
    cfg = load_config(args.config)
    inp = Path(args.packets).expanduser()
    if not inp.is_file():
        raise FileNotFoundError(inp)
    outdir = Path(args.out).expanduser()
    outdir.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(inp)
    validate_packets(df)
    if "shift_days" not in df.columns:
        df["shift_days"] = 0
    df = df[df["window"].isin(WINDOW_ORDER)].copy()
    df = df.sort_values(["shift_days", "width", "dpc_start", "packet_index"]).reset_index(drop=True)
    if df.empty:
        raise ValueError("No usable W1..F3 packets")

    ablations = list(dict.fromkeys(args.ablate))
    res = run_model(df, cfg, ablations, int(args.top_contributors))

    with open(outdir / "model_config_used.json", "w", encoding="utf-8") as f:
        json.dump(cfg, f, ensure_ascii=False, indent=2)
    with open(outdir / "formal_spec_manifest.json", "w", encoding="utf-8") as f:
        json.dump(formal_spec_manifest(cfg), f, ensure_ascii=False, indent=2)
    with open(outdir / "invariants_manifest.json", "w", encoding="utf-8") as f:
        json.dump({"version": VERSION, "invariants": INVARIANTS}, f, ensure_ascii=False, indent=2)
    with open(outdir / "lesion_manifest.json", "w", encoding="utf-8") as f:
        json.dump({
            "version": VERSION,
            "status": "behavioral lesion expectations from master spec; developmental ablations below are only engineering sensitivity tests",
            "expected_failure_modes": LESION_EXPECTATIONS,
            "developmental_ablation_groups": {k: sorted(v) for k, v in ABLATION_TARGETS.items()},
            "structural_noop_ablations": ["PROVENANCE", "W_MIN"],
        }, f, ensure_ascii=False, indent=2)

    parameter_definition_table(cfg).to_csv(outdir / "parameter_definitions.csv", index=False)
    developmental_map_table(cfg).to_csv(outdir / "developmental_parameter_map.csv", index=False)
    res["packet"].to_csv(outdir / "packet_drivers.csv", index=False)
    res["brain"].to_csv(outdir / "brain_circuit_trajectory.csv", index=False)
    res["trajectory"].to_csv(outdir / "machine_parameter_trajectory.csv", index=False)
    res["finals"].to_csv(outdir / "machine_profile_by_run.csv", index=False)
    res["ensemble"].to_csv(outdir / "machine_profile_ensemble.csv", index=False)
    res["brain_ensemble"].to_csv(outdir / "brain_exposure_ensemble.csv", index=False)
    res["window_summary"].to_csv(outdir / "window_cascade_summary.csv", index=False)
    with open(outdir / "H_star_vector.json", "w", encoding="utf-8") as f:
        json.dump(res["hstar"], f, ensure_ascii=False, indent=2)
    with open(outdir / "explanation_graph.json", "w", encoding="utf-8") as f:
        json.dump(res["graph"], f, ensure_ascii=False, indent=2)

    if args.ablation_suite:
        abl = ablation_suite(df, cfg, res["ensemble"], int(args.top_contributors))
        abl.to_csv(outdir / "ablation_sensitivity.csv", index=False)

    print(f"ARCHVIQ developmental brain -> RS4/v4 cascade {VERSION}")
    print(f"Input: {inp}")
    print(f"Ablations: {ablations if ablations else 'NONE'}")
    print(f"Runs: {res['finals'][['shift_days','width']].drop_duplicates().shape[0]}")
    print(f"Packets: {len(res['packet'])}")
    print(f"Parameters: {len(cfg['parameter_definitions'])}")
    print(f"Output: {outdir}")
    show = res["ensemble"][["parameter", "mode", "state_median", "state_min", "state_max", "pressure_median"]]
    print("\nH* calibration vector summary:")
    print(show.to_string(index=False, float_format=lambda x: f"{x: .3f}"))


if __name__ == "__main__":
    main()
